/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:874116dc-74d6-4063-97bb-8f2d1921bef4",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_pvu7HoIPo",
    "aws_user_pools_web_client_id": "6v48gj2kn2o1ho5uht5nj4d91",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "visualizinggcnsapp-storage192454-prod",
    "aws_user_files_s3_bucket_region": "sa-east-1"
};


export default awsmobile;
